language: node_js
node_js:
  - "6.*"
cache:
  directories:
    - node_modules
    - dist
    - cache
branches:
  only:
    - master
before_install:
  - export TZ=Asia/Tokyo
before_script:
  - git config --global user.name "Travis CI"
  - git config --global user.email "cognitom@gmail.com"
  - openssl aes-256-cbc -K $encrypted_071a486c2ea0_key -iv $encrypted_071a486c2ea0_iv -in deploy-key.enc -out deploy-key -d
  - chmod 600 deploy-key
  - ssh-add deploy-key
script:
  - npm test
  - npm run deploy-from-travis
