language: node_js
node_js:
  - "6.*"
cache:
  directories:
    - node_modules
    - dist
branches:
  only:
    - master
before_install:
  - export TZ=Asia/Tokyo
before_script:
  - git config --global user.name "$GIT_NAME"
  - git config --global user.email "$GIT_EMAIL"
script:
  - npm test
  - npm run deploy-from-travis
