language: node_js
node_js:
  - "6.*"
cache:
  directories:
    - node_modules
    - dist
branches:
  only:
    - master
before_install:
  - export TZ=Asia/Tokyo
after_success:
  npm run deploy-from-travis
