language: node_js
node_js:
  - "6.*"
cache:
  directories:
    - node_modules
    - dist
    - cache
branches:
  only:
    - master
before_install:
  - export TZ=Asia/Tokyo
before_script:
  - git config --global user.name "cognitom"
  - git config --global user.email "cognitom@gmail.com"
  - git config remote.origin.url git@github.com:cognitom/shinkan.today.git
  - openssl aes-256-cbc -K $encrypted_071a486c2ea0_key -iv $encrypted_071a486c2ea0_iv -in deploy-key.enc -out deploy-key -d
  - chmod 600 deploy-key
  - eval "$(ssh-agent -s)"
  - ssh-add deploy-key
script:
  - npm test
  - npm run build
  - npm run update
  - git config --global --list
  - git config --local --list
  - ls -al # for debugging
  - ls -al dist # for debugging
  - npm run deploy
